#!/bin/bash

set -eou pipefail

buck test
buck build src/net/digihippo/ltt/android:livetraintimes
rm -f *.apk
${ANDROID_SDK}/build-tools/23.0.2/zipalign 4 buck-out/gen/src/net/digihippo/ltt/android/livetraintimes.apk livetraintimes.signed.aligned.apk