java_library(
  name = 'live-trains-api',
  srcs = glob(['*.java']),
  deps = [
    '//src/net/digihippo/ltt/soap:soap-trains',
    '//:guava',
    '//:jsr-305',
    '//:jodatime',
    '//:ksoap',
  ],
  visibility = [ 'PUBLIC' ],
)