prebuilt_jar(
  name = 'junit',
  binary_jar = 'junit-4.12.jar',
  visibility = [ 'PUBLIC' ]
)

prebuilt_jar(
  name = 'hamcrest-core',
  binary_jar = 'hamcrest-core-1.3.jar',
  visibility = [ 'PUBLIC' ]
)

prebuilt_jar(
  name = 'hamcrest-library',
  binary_jar = 'hamcrest-library-1.3.jar',
  visibility = [ 'PUBLIC' ]
)