package net.digihippo.ltt.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class WWHServiceDetails extends AttributeContainer implements KvmSerializable
{

    
    public java.util.Date generatedAt;
    
    public WWHEnums.ServiceType serviceType=WWHEnums.ServiceType.train;
    
    public String locationName;
    
    public String crs;
    
    public String _operator;
    
    public String operatorCode;
    
    public Boolean isCancelled;
    
    public String disruptionReason;
    
    public String overdueMessage;
    
    public String platform;
    
    public String sta;
    
    public String eta;
    
    public String ata;
    
    public String std;
    
    public String etd;
    
    public String atd;
    
    public WWHArrayOfAdhocAlert adhocAlerts=new WWHArrayOfAdhocAlert();
    
    public WWHArrayOfArrayOfCallingPoints previousCallingPoints=new WWHArrayOfArrayOfCallingPoints();
    
    public WWHArrayOfArrayOfCallingPoints subsequentCallingPoints=new WWHArrayOfArrayOfCallingPoints();

    public WWHServiceDetails ()
    {
    }

    public WWHServiceDetails (Object paramObj,WWHExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("generatedAt"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.generatedAt = WWHHelper.ConvertFromWebService(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof java.util.Date){
                        this.generatedAt = (java.util.Date)obj;
                    }
                    continue;
                }
                if (info.name.equals("serviceType"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.serviceType = WWHEnums.ServiceType.fromString(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof WWHEnums.ServiceType){
                        this.serviceType = (WWHEnums.ServiceType)obj;
                    }
                    continue;
                }
                if (info.name.equals("locationName"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.locationName = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.locationName = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("crs"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.crs = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.crs = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("operator"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this._operator = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this._operator = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("operatorCode"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.operatorCode = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.operatorCode = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("isCancelled"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.isCancelled = new Boolean(j.toString());
                        }
                    }
                    else if (obj!= null && obj instanceof Boolean){
                        this.isCancelled = (Boolean)obj;
                    }
                    continue;
                }
                if (info.name.equals("disruptionReason"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.disruptionReason = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.disruptionReason = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("overdueMessage"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.overdueMessage = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.overdueMessage = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("platform"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.platform = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.platform = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("sta"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.sta = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.sta = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("eta"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.eta = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.eta = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("ata"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.ata = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.ata = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("std"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.std = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.std = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("etd"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.etd = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.etd = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("atd"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.atd = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.atd = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("adhocAlerts"))
                {
                    Object j = obj;
                    this.adhocAlerts = new WWHArrayOfAdhocAlert(j,__envelope);
                    continue;
                }
                if (info.name.equals("previousCallingPoints"))
                {
                    Object j = obj;
                    this.previousCallingPoints = new WWHArrayOfArrayOfCallingPoints(j,__envelope);
                    continue;
                }
                if (info.name.equals("subsequentCallingPoints"))
                {
                    Object j = obj;
                    this.subsequentCallingPoints = new WWHArrayOfArrayOfCallingPoints(j,__envelope);
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.generatedAt!=null?WWHHelper.getDateTimeFormat().format(this.generatedAt):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.serviceType!=null?this.serviceType.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return locationName;
        }
        if(propertyIndex==3)
        {
            return crs;
        }
        if(propertyIndex==4)
        {
            return _operator;
        }
        if(propertyIndex==5)
        {
            return operatorCode;
        }
        if(propertyIndex==6)
        {
            return this.isCancelled!=null?this.isCancelled:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.disruptionReason!=null?this.disruptionReason:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.overdueMessage!=null?this.overdueMessage:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.platform!=null?this.platform:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.sta!=null?this.sta:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.eta!=null?this.eta:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.ata!=null?this.ata:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.std!=null?this.std:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==14)
        {
            return this.etd!=null?this.etd:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==15)
        {
            return this.atd!=null?this.atd:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==16)
        {
            return this.adhocAlerts!=null?this.adhocAlerts:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==17)
        {
            return this.previousCallingPoints!=null?this.previousCallingPoints:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==18)
        {
            return this.subsequentCallingPoints!=null?this.subsequentCallingPoints:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 19;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "generatedAt";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "serviceType";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "locationName";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "crs";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "operator";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "operatorCode";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "isCancelled";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "disruptionReason";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "overdueMessage";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "platform";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "sta";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "eta";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ata";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "std";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==14)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "etd";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==15)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "atd";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==16)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "adhocAlerts";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==17)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "previousCallingPoints";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
        if(propertyIndex==18)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "subsequentCallingPoints";
            info.namespace= "http://thalesgroup.com/RTTI/2014-02-20/ldb/types";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
