package net.digihippo.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;
import java.util.Vector;


public class WWHArrayOfServiceItemsWithCallingPoints extends Vector< WWHServiceItemWithCallingPoints> implements KvmSerializable
{
    
    public WWHArrayOfServiceItemsWithCallingPoints(){}
    
    public WWHArrayOfServiceItemsWithCallingPoints(Object inObj,WWHExtendedSoapSerializationEnvelope __envelope)
    {
        if (inObj == null)
            return;
        SoapObject soapObject=(SoapObject)inObj;
        int size = soapObject.getPropertyCount();
        for (int i0=0;i0< size;i0++)
        {
            Object obj = soapObject.getProperty(i0);
            if (obj!=null && obj instanceof AttributeContainer)
            {
                AttributeContainer j =(AttributeContainer) soapObject.getProperty(i0);
                WWHServiceItemWithCallingPoints j1= (WWHServiceItemWithCallingPoints)__envelope.get(j,WWHServiceItemWithCallingPoints.class);
                add(j1);
            }
        }
}
    
    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0)!=null?this.get(arg0):SoapPrimitive.NullNilElement;
    }
    
    @Override
    public int getPropertyCount() {
        return this.size();
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "service";
        info.type = WWHServiceItemWithCallingPoints.class;
    	info.namespace= "http://thalesgroup.com/RTTI/2015-05-14/ldb/types";
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}