package net.digihippo.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class WWHCallingPoint extends AttributeContainer implements KvmSerializable
{

    
    public String locationName;
    
    public String crs;
    
    public String st;
    
    public String et;
    
    public String at;
    
    public WWHArrayOfAdhocAlert adhocAlerts=new WWHArrayOfAdhocAlert();

    public WWHCallingPoint ()
    {
    }

    public WWHCallingPoint (Object paramObj,WWHExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("locationName"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.locationName = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.locationName = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("crs"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.crs = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.crs = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("st"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.st = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.st = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("et"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.et = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.et = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("at"))
                {
        
                    if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.at = j.toString();
                        }
                    }
                    else if (obj!= null && obj instanceof String){
                        this.at = (String)obj;
                    }
                    continue;
                }
                if (info.name.equals("adhocAlerts"))
                {
                    Object j = obj;
                    this.adhocAlerts = new WWHArrayOfAdhocAlert(j,__envelope);
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return locationName;
        }
        if(propertyIndex==1)
        {
            return crs;
        }
        if(propertyIndex==2)
        {
            return this.st!=null?this.st:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.et!=null?this.et:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.at!=null?this.at:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.adhocAlerts!=null?this.adhocAlerts:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "locationName";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "crs";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "st";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "et";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "at";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "adhocAlerts";
            info.namespace= "http://thalesgroup.com/RTTI/2012-01-13/ldb/types";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
