package net.digihippo.soap;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import com.google.common.base.Function;
import com.google.common.base.Joiner;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;
import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;
import org.ksoap2.transport.Transport;
import org.kxml2.kdom.Element;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class WWHLDBServiceSoap
{
    interface WWHIWcfMethod
    {
        WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://lite.realtime.nationalrail.co.uk/OpenLDBWS/ldb7.asmx";

    int timeOut=15000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    public WWHLDBServiceSoap(){}

    public WWHLDBServiceSoap(String url)
    {
        this.url = url;
    }

    public WWHLDBServiceSoap(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    public static void main(String[] args) throws Exception {
        WWHLDBServiceSoap wwhldbServiceSoap = new WWHLDBServiceSoap();

        WWHAccessToken accessToken = new WWHAccessToken();
        accessToken.TokenValue = "dcfa2a36-cb60-4e03-9264-c9544446945f";
        WWHStationBoardWithDetails board = wwhldbServiceSoap.GetDepBoardWithDetails(
                20, "VIC", null, null, null, null, accessToken
        );

        WWHArrayOfServiceItemsWithCallingPoints trainServices = board.trainServices;
        for (WWHServiceItemWithCallingPoints trainService : trainServices) {
            System.out.println(
                    Joiner.on(", ").join(
                            Lists.transform(trainService.destination, new Function<WWHServiceLocation, String>() {
                                @Override
                                public String apply(WWHServiceLocation wwhServiceLocation) {
                                    return wwhServiceLocation.locationName;
                                }
                            })

            ));
            for (WWHArrayOfCallingPoints subsequentCallingPoint : trainService.subsequentCallingPoints) {
                Iterable<String> callingPoint =
                        Iterables.transform(subsequentCallingPoint.callingPoint, new Function<WWHCallingPoint, String>() {
                            @Override
                            public String apply(WWHCallingPoint wwhCallingPoint) {
                                return wwhCallingPoint.locationName + " @ " + wwhCallingPoint.st;
                            }
                        });
                System.out.println("CP: " + Joiner.on(", ").join(callingPoint));
            }
        }
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected WWHExtendedSoapSerializationEnvelope createEnvelope()
    {
        WWHExtendedSoapSerializationEnvelope envelope= new WWHExtendedSoapSerializationEnvelope(WWHExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected List sendRequest(String methodName,WWHExtendedSoapSerializationEnvelope envelope,Transport transport  )throws Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    Object getResult(Class destObj,Object source,String resultName,WWHExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public WWHStationBoard GetDepartureBoard(final Integer numRows,final String crs,final String filterCrs,final WWHEnums.FilterType filterType,final Integer timeOffset,final Integer timeWindow,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHStationBoard)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetDepartureBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="numRows";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="crs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterCrs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs!=null?filterCrs:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterType!=null?filterType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeOffset";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset!=null?timeOffset:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeWindow";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow!=null?timeWindow:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHStationBoard)getResult(WWHStationBoard.class,__result,"GetStationBoardResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2012-01-13/ldb/GetDepartureBoard");
    }
    
    public WWHStationBoard GetArrivalBoard(final Integer numRows,final String crs,final String filterCrs,final WWHEnums.FilterType filterType,final Integer timeOffset,final Integer timeWindow,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHStationBoard)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetArrivalBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="numRows";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="crs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterCrs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs!=null?filterCrs:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterType!=null?filterType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeOffset";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset!=null?timeOffset:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeWindow";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow!=null?timeWindow:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHStationBoard)getResult(WWHStationBoard.class,__result,"GetStationBoardResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalBoard");
    }
    
    public WWHStationBoard GetArrivalDepartureBoard(final Integer numRows,final String crs,final String filterCrs,final WWHEnums.FilterType filterType,final Integer timeOffset,final Integer timeWindow,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHStationBoard)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetArrivalDepartureBoardRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="numRows";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="crs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterCrs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs!=null?filterCrs:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterType!=null?filterType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeOffset";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset!=null?timeOffset:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeWindow";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow!=null?timeWindow:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHStationBoard)getResult(WWHStationBoard.class,__result,"GetStationBoardResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2012-01-13/ldb/GetArrivalDepartureBoard");
    }
    
    public WWHServiceDetails GetServiceDetails(final String serviceID,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHServiceDetails)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetServiceDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="serviceID";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(serviceID);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHServiceDetails)getResult(WWHServiceDetails.class,__result,"GetServiceDetailsResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2012-01-13/ldb/GetServiceDetails");
    }
    
    public WWHStationBoardWithDetails GetDepBoardWithDetails(final Integer numRows,final String crs,final String filterCrs,final WWHEnums.FilterType filterType,final Integer timeOffset,final Integer timeWindow,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHStationBoardWithDetails)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetDepBoardWithDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="numRows";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="crs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterCrs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs!=null?filterCrs:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterType!=null?filterType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeOffset";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset!=null?timeOffset:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeWindow";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow!=null?timeWindow:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHStationBoardWithDetails)getResult(WWHStationBoardWithDetails.class,__result,"GetStationBoardResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2015-05-14/ldb/GetDepBoardWithDetails");
    }
    
    public WWHStationBoardWithDetails GetArrBoardWithDetails(final Integer numRows,final String crs,final String filterCrs,final WWHEnums.FilterType filterType,final Integer timeOffset,final Integer timeWindow,final WWHAccessToken AccessToken ) throws Exception
    {
        return (WWHStationBoardWithDetails)execute(new WWHIWcfMethod()
        {
            @Override
            public WWHExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              WWHExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                ArrayList< Element> __headers=null;
                if(__envelope.headerOut==null)
                {
                    __headers = new ArrayList< Element>();
                }
                else
                {
                    __headers = new ArrayList< Element>(Arrays.asList(__envelope.headerOut));
                }
                __headers.add(WWHHelper.convertToHeader(AccessToken!=null?AccessToken:SoapPrimitive.NullNilElement,"http://thalesgroup.com/RTTI/2013-11-28/Token/types","AccessToken"));
                __envelope.headerOut = __headers.toArray(new Element[__headers.size()]);
                SoapObject __soapReq = new SoapObject("http://thalesgroup.com/RTTI/2015-05-14/ldb/", "GetArrBoardWithDetailsRequest");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="numRows";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(numRows);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="crs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(crs);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterCrs";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterCrs!=null?filterCrs:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="filterType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(filterType!=null?filterType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeOffset";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeOffset!=null?timeOffset:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://thalesgroup.com/RTTI/2015-05-14/ldb/";
                __info.name="timeWindow";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(timeWindow!=null?timeWindow:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(WWHExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (WWHStationBoardWithDetails)getResult(WWHStationBoardWithDetails.class,__result,"GetStationBoardResult",__envelope);
            }
        },"http://thalesgroup.com/RTTI/2015-05-14/ldb/GetArrBoardWithDetails");
    }
    
    public String GetArrDepBoardWithDetails(final String numRows,final String crs,final String filterCrs,final String filterType,final String timeOffset,final String timeWindow,final String AccessToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetNextDepartures(final String crs,final String filterList,final String timeOffset,final String timeWindow,final String AccessToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetNextDeparturesWithDetails(final String crs,final String filterList,final String timeOffset,final String timeWindow,final String AccessToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetFastestDepartures(final String crs,final String filterList,final String timeOffset,final String timeWindow,final String AccessToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public String GetFastestDeparturesWithDetails(final String crs,final String filterList,final String timeOffset,final String timeWindow,final String AccessToken ) throws Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }

    
    protected Object execute(WWHIWcfMethod wcfMethod,String methodName) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        WWHExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
        
    Exception convertToException(org.ksoap2.SoapFault fault,WWHExtendedSoapSerializationEnvelope envelope)
    {
        return new Exception(fault.faultstring);
    }
}


