package net.digihippo.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.SoapPrimitive;

public class WWHNRCCMessage  
{

    
    public String value;

    public WWHNRCCMessage ()
    {
    }

    public WWHNRCCMessage (Object paramObj,WWHExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;

        if(inObj!=null)
        {
            Object j =(Object)inObj;
            Object obj=inObj;
            value = j.toString();
        }

    }
    public Object getSimpleValue()
    {
        Object j=this.value;
        SoapPrimitive primitive = new SoapPrimitive("http://thalesgroup.com/RTTI/2012-01-13/ldb/types", "value",j!=null?j.toString():"");
        return primitive;
    }}
