package net.digihippo.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.1
//
// Created by Quasar Development at 02-12-2015
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class WWHStationBoard extends WWHBaseStationBoard implements KvmSerializable
{

    
    public WWHArrayOfServiceItems trainServices=new WWHArrayOfServiceItems();
    
    public WWHArrayOfServiceItems busServices=new WWHArrayOfServiceItems();
    
    public WWHArrayOfServiceItems ferryServices=new WWHArrayOfServiceItems();

    public WWHStationBoard ()
    {
    }

    public WWHStationBoard (Object paramObj,WWHExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("trainServices"))
                {
                    Object j = obj;
                    this.trainServices = new WWHArrayOfServiceItems(j,__envelope);
                    continue;
                }
                if (info.name.equals("busServices"))
                {
                    Object j = obj;
                    this.busServices = new WWHArrayOfServiceItems(j,__envelope);
                    continue;
                }
                if (info.name.equals("ferryServices"))
                {
                    Object j = obj;
                    this.ferryServices = new WWHArrayOfServiceItems(j,__envelope);
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.trainServices!=null?this.trainServices:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.busServices!=null?this.busServices:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.ferryServices!=null?this.ferryServices:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "trainServices";
            info.namespace= "http://thalesgroup.com/RTTI/2015-05-14/ldb/types";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "busServices";
            info.namespace= "http://thalesgroup.com/RTTI/2015-05-14/ldb/types";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ferryServices";
            info.namespace= "http://thalesgroup.com/RTTI/2015-05-14/ldb/types";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

}
