java_library(
  name = 'soap-trains',
  srcs = glob(['*.java']),
  deps = [
    '//:ksoap',
    '//:guava',
    '//:jsr-305',

    '//src/net/digihippo/ltt:live-trains-api'
  ],
  visibility = [ 'PUBLIC' ],
)